# Generated by Django 5.2.7 on 2025-10-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('buffalo', 'Buffalo'), ('plant', 'Plant-based'), ('other', 'Other')], default='cow', max_length=20)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_vegan', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cheese',
                'verbose_name_plural': 'Cheeses',
                'ordering': ['name'],
            },
        ),
    ]
