# Generated by Django 5.2.7 on 2025-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheese_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='slug',
            field=models.SlugField(default='xxx', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
